Update Jenkinsfile-dev

diff --git a/Jenkinsfile-dev b/Jenkinsfile-dev
--- a/Jenkinsfile-dev
+++ b/Jenkinsfile-dev
@@ -12,6 +12,25 @@ pipeline {
     }
 
     stages {
+        stage('Parameters'){
+            steps {
+                script {
+                properties([
+                        parameters([
+                            [$class: 'booleanParameter', 
+                                choiceType: 'PT_CHECKBOX', 
+                                description: 'Run tests?', 
+                                filterLength: 1, 
+                                filterable: false, 
+                                name: 'RunTests',
+                                checked: true
+                            ],
+
+                    ]),
+                    ])
+                }
+            }
+        }
         
         stage('Clean target directory') {
             steps {
@@ -21,6 +40,23 @@ pipeline {
             }
         }
 
+        if(params.RunTests) {
+            stage('Unit Tests') {
+                steps {
+                    // Executa os testes unitários
+                    echo 'Running unit tests'
+                    sh 'mvn test'
+                }
+            }
+
+            stage('Mutation Tests') {
+                steps {
+                    // Executa os testes de mutação
+                    echo 'Running mutation tests'
+                    sh 'mvn org.pitest:pitest-maven:mutationCoverage'
+                }
+            }
+        }
         stage('Package') {
             steps {
                 // Empacota o projeto sem executar os testes novamente
@@ -31,57 +67,60 @@ pipeline {
 
         stage('Deploy Application') {
             steps {
-                // Mata o processo se estiver em execução, copia o novo arquivo JAR para a pasta de deploy e inicia a aplicação
-                echo 'Kill the application if it is running'
-                
-                sh '''
-                    # Obtem o PID do processo
-                    process=$(netstat -aon | grep :$SERVER_PORT | awk '{print $5}' | head -n 1)
+                script{
+                    // Mata o processo se estiver em execução, copia o novo arquivo JAR para a pasta de deploy e inicia a aplicação
+                    echo 'Kill the application if it is running'
                     
-                    # Verifica se o processo foi encontrado e termina o processo
-                    if [ -n "$process" ]; then
-                        echo "Killing process with PID: $process"
-                        taskkill //PID $process //F
-                    else
-                        echo "No process found running in port $SERVER_PORT"
-                    fi
-                '''
-
-                echo 'Deploying the application'
-                sh '''                    
-                    # Cria a pasta de deploy se não existir
-                    mkdir -p $DEPLOY_DIR
-                    
-                    # Verifica se o arquivo JAR existe na pasta target
-                    if [ -f "target/psoft-g1-0.0.1-SNAPSHOT.jar" ]; then
+                    sh '''
+                        # Obtem o PID do processo
+                        process=$(netstat -aon | grep :$SERVER_PORT | awk '{print $5}' | head -n 1)
                         
-                        # Se o JAR já existir na pasta de deploy, apaga-o
-                        if [ -f "$DEPLOY_DIR/psoft-g1-0.0.1-SNAPSHOT.jar" ]; then
-                            echo "Removing existing JAR in deploy directory..."
-                            rm "$DEPLOY_DIR/psoft-g1-0.0.1-SNAPSHOT.jar"
+                        # Verifica se o processo foi encontrado e termina o processo
+                        if [ -n "$process" ]; then
+                            echo "Killing process with PID: $process"
+                            taskkill //PID $process //F
+                        else
+                            echo "No process found running in port $SERVER_PORT"
                         fi
-                        
-                        # Copia o novo arquivo JAR para a pasta de deploy
-                        cp target/psoft-g1-0.0.1-SNAPSHOT.jar $DEPLOY_DIR/
-                        
-                        # Muda para a pasta de deploy
-                        cd $DEPLOY_DIR
-                        
-                        echo "Starting the application..."
-                        
-                        # Inicia a aplicação em segundo plano a partir da pasta de deploy
-                        
-                        echo "Application started in background on port $SERVER_PORT"
-                    else
-                        echo "Error: psoft-g1-0.0.1-SNAPSHOT.jar not found in target!"
-                        exit 1
-                    fi
-                '''
+                    '''
 
-                sh '''
-                    cd $DEPLOY_DIR
-                    nohup java -jar psoft-g1-0.0.1-SNAPSHOT.jar --server.port=$SERVER_PORT > app.log 2>&1&
-                '''
+                    echo 'Deploying the application'
+                    sh '''                    
+                        # Cria a pasta de deploy se não existir
+                        mkdir -p $DEPLOY_DIR
+                        
+                        # Verifica se o arquivo JAR existe na pasta target
+                        if [ -f "target/psoft-g1-0.0.1-SNAPSHOT.jar" ]; then
+                            
+                            # Se o JAR já existir na pasta de deploy, apaga-o
+                            if [ -f "$DEPLOY_DIR/psoft-g1-0.0.1-SNAPSHOT.jar" ]; then
+                                echo "Removing existing JAR in deploy directory..."
+                                rm "$DEPLOY_DIR/psoft-g1-0.0.1-SNAPSHOT.jar"
+                            fi
+                            
+                            # Copia o novo arquivo JAR para a pasta de deploy
+                            cp target/psoft-g1-0.0.1-SNAPSHOT.jar $DEPLOY_DIR/
+                            
+                            # Muda para a pasta de deploy
+                            cd $DEPLOY_DIR
+                            
+                            echo "Starting the application..."
+                            
+                            # Inicia a aplicação em segundo plano a partir da pasta de deploy
+                            
+                            echo "Application started in background on port $SERVER_PORT"
+                        else
+                            echo "Error: psoft-g1-0.0.1-SNAPSHOT.jar not found in target!"
+                            exit 1
+                        fi
+                    '''
+
+                    sh '''
+                        cd $DEPLOY_DIR
+                        nohup java -jar psoft-g1-0.0.1-SNAPSHOT.jar --server.port=$SERVER_PORT > app.log 2>&1&
+                    '''
+
+                    }   
             }
         }
 
